#ifndef COR_DICT_H
#define COR_DICT_H

#include "Judy.h"

#include "cor_core.h"
#include "cor_log.h"
#include "cor_pool.h"
#include "cor_str.h"

enum
{
    COR_DICT_GRM_UNKNOWN = 0,
    COR_DICT_GRM_NOUN, COR_DICT_GRM_ADJF, COR_DICT_GRM_ADJS, COR_DICT_GRM_COMP, COR_DICT_GRM_VERB,
    COR_DICT_GRM_INFN, COR_DICT_GRM_PRTF, COR_DICT_GRM_PRTS, COR_DICT_GRM_GRND, COR_DICT_GRM_NUMR,
    COR_DICT_GRM_ADVB, COR_DICT_GRM_NPRO, COR_DICT_GRM_PRED, COR_DICT_GRM_PREP, COR_DICT_GRM_CONJ,
    COR_DICT_GRM_PRCL, COR_DICT_GRM_INTJ, COR_DICT_GRM_ANIM, COR_DICT_GRM_INAN, COR_DICT_GRM_GNDR,
    COR_DICT_GRM_MASC, COR_DICT_GRM_FEMN, COR_DICT_GRM_NEUT, COR_DICT_GRM_MS_F, COR_DICT_GRM_SING,
    COR_DICT_GRM_PLUR, COR_DICT_GRM_SGTM, COR_DICT_GRM_PLTM, COR_DICT_GRM_FIXD, COR_DICT_GRM_NOMN,
    COR_DICT_GRM_GENT, COR_DICT_GRM_DATV, COR_DICT_GRM_ACCS, COR_DICT_GRM_ABLT, COR_DICT_GRM_LOCT,
    COR_DICT_GRM_VOCT, COR_DICT_GRM_GEN1, COR_DICT_GRM_GEN2, COR_DICT_GRM_ACC2, COR_DICT_GRM_LOC1,
    COR_DICT_GRM_LOC2, COR_DICT_GRM_ABBR, COR_DICT_GRM_NAME, COR_DICT_GRM_SURN, COR_DICT_GRM_PATR,
    COR_DICT_GRM_GEOX, COR_DICT_GRM_ORGN, COR_DICT_GRM_TRAD, COR_DICT_GRM_SUBX, COR_DICT_GRM_SUPR,
    COR_DICT_GRM_QUAL, COR_DICT_GRM_APRO, COR_DICT_GRM_ANUM, COR_DICT_GRM_POSS, COR_DICT_GRM_V_EY,
    COR_DICT_GRM_V_OY, COR_DICT_GRM_CMP2, COR_DICT_GRM_V_EJ, COR_DICT_GRM_PERF, COR_DICT_GRM_IMPF,
    COR_DICT_GRM_TRAN, COR_DICT_GRM_INTR, COR_DICT_GRM_IMPE, COR_DICT_GRM_IMPX, COR_DICT_GRM_MULT,
    COR_DICT_GRM_REFL, COR_DICT_GRM_PERS, COR_DICT_GRM_1PER, COR_DICT_GRM_2PER, COR_DICT_GRM_3PER,
    COR_DICT_GRM_PRES, COR_DICT_GRM_PAST, COR_DICT_GRM_FUTR, COR_DICT_GRM_INDC, COR_DICT_GRM_IMPR,
    COR_DICT_GRM_INCL, COR_DICT_GRM_EXCL, COR_DICT_GRM_ACTV, COR_DICT_GRM_PSSV, COR_DICT_GRM_INFR,
    COR_DICT_GRM_SLNG, COR_DICT_GRM_ARCH, COR_DICT_GRM_LITR, COR_DICT_GRM_ERRO, COR_DICT_GRM_DIST,
    COR_DICT_GRM_QUES, COR_DICT_GRM_DMNS, COR_DICT_GRM_PRNT, COR_DICT_GRM_V_BE, COR_DICT_GRM_V_EN,
    COR_DICT_GRM_V_IE, COR_DICT_GRM_V_BI, COR_DICT_GRM_FIMP, COR_DICT_GRM_PRDX, COR_DICT_GRM_COUN,
    COR_DICT_GRM_COLL, COR_DICT_GRM_V_SH, COR_DICT_GRM_AF_P, COR_DICT_GRM_INMX, COR_DICT_GRM_VPRE,
    COR_DICT_GRM_ANPH, COR_DICT_GRM_INIT, COR_DICT_GRM_ADJX
};

typedef struct
{
    cor_str_t *base;
    int *gramemmes;
} cor_dict_word_t;

typedef struct
{
    unsigned delete_pool:1;

    Pvoid_t words;
    Pvoid_t gramemmes_by_key;
    Pvoid_t gramemmes_hash;

    cor_pool_t *pool;
    cor_log_t *log;
} cor_dict_t;

cor_dict_t *cor_dict_new(cor_pool_t *pool, cor_log_t *log);
void cor_dict_delete(cor_dict_t *dict);
int cor_dict_load_opencorpa(cor_dict_t *dict, const char *file);
int cor_dict_get_gramemme_id(cor_dict_t *dict, const char *gramemme, size_t size);
cor_dict_word_t *cor_dict_get_word(cor_dict_t *dict, const char *word);
void cor_dict_dump(cor_dict_t *dict);

#endif
